version: "3.9" #opsiyonel

services:

  frontend:
    # container_name: frontend (default: keyName)
    image: "docker-compose-frontend"
    build: ./frontend
    ports:
      #dis/ic port numaralari
      - 5173:5173
      - 3000:5173
      - 80:5173
    restart: on-failure # haata aninda tekrar calistir.
    depends_on:
      #once asagidakileri calistir.
      _ backend # asagida tanimlandi.

  backend:
    image: "docker-compose-backend"
    build: ./backend
    ports:
      - 8000:8000
    restart: on-failure # haata aninda tekrar calistir.
